version: "3.9"
services:
  bcb-server:
    image: python:3.12-slim
    command: python /opt/server.py
    ports:
      - "8000:8000"
    volumes:
      - "./server:/opt"
  client:
    build: .
    environment:
      - PIX_BCB_BASE_URL=http://bcb-server:8000
