# .github/workflows/release.yml
name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install build deps
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Build wheel
      run: python -m build --wheel

    # -------- Criar Release no GitHub --------
    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        name: "Pix Client ${{ github.ref_name }}"
        generate_release_notes: true

    - name: Upload wheel to Release
      uses: softprops/action-gh-release@v2
      with:
        files: dist/*.whl
